# Usage:
# docker-compose -f orchestration_less_accounting_collector.yml up -d cadvisor
# NB: You may have to run `chown 1000:1000 ./elasticsearch-data` for the 
# elasticsearch service to work

version: '3'
services:
  cadvisor:
    container_name: container_accounting_cadvisor
    image: gcr.io/google-containers/cadvisor:v0.35.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 80:8080
  elasticsearch:
    container_name: container_accounting_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
