language: python
python:
  - "2.7"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
  fast_finish: true

# Route build to container-based infrastructure
sudo: false

# Cache the dependencies installed by pip
cache: pip
# Avoid pip log from affecting cache
before_cache: rm -fv ~/.cache/pip/log/debug.log

services:
  - elasticsearch

# Install defaults to "pip install -r requirements.txt"

before_script:
  # Give ElasticSearch enough time to start, as per:
  # https://docs.travis-ci.com/user/database-setup/#elasticsearch
  - sleep 10
  - export PYTHONPATH=$PYTHONPATH:`pwd -P`
  - cd test

script:
  - coverage run --branch --source=rac,bin -m unittest2 discover --buffer

after_success:
  - coveralls
