version: '3'
services:
  container_accounting_collector:
    image: gregcorbett/container_accounting_collector:containerization
    volumes:
      - ${PWD}/conf:/etc/apel:ro
      - ${PWD}/rancher_agent.log:/usr/share/container_accounting/rancher_agent.log:ro

volumes:
  conf:
